version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/stripe-rails
    image: stripe-rails:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    env_file:
      - '.env.dev'
    ports:
      - "3000:3000"
    depends_on:
      - db
  background:
    build: .
    volumes:
      - .:/stripe-rails
    image: stripe-rails:latest
    command: bundle exec rake jobs:work
    env_file:
      - '.env.dev'
    depends_on:
      - db
  db:
    image: postgres:14.3
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  # test:
  #   build:
  #     context: .
  #     cache_from:
  #       - stripe-rails:latest
  #   image: stripe-rails:latest
  #   volumes:
  #     - .:/stripe-rails
  #   command: bundle exec rspec
  #   env_file:
  #     - '.env.test'
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - db
  #   profiles: ["test"]
